language: python
python:
 - "3.6.1"
 
# Add these lines after the install section 

dist: trusty
sudo: required

addons:
 sonarcloud:
  organization: "team7-ssw567-triangle567"
  token: "70198bdeaecec804b804b902cf17598e820b5744"
  branches:
  - sonarcloud
 
# add the sonar-scanner command after all the other commands that you already have
script:
 - python -m unittest TestTriangle
 - sonar-scanner
